In [2]:
pip install opencv-python

Note: you may need to restart the kernel to use updated packages.


In [25]:
import cv2

image = cv2.imread("Berlin.jpg")
print(image.shape)

(900, 1600, 3)


In [26]:
print(image[:2])

[[[  3 141 130]
  [  3 132 129]
  [  6 131 135]
  ...
  [205 179 163]
  [205 179 163]
  [205 179 163]]

 [[  0 139 129]
  [  0 136 131]
  [  4 136 136]
  ...
  [205 179 163]
  [205 179 163]
  [205 179 163]]]


In [27]:
print(image.dtype)

uint8


# Task: Do the following image transformation using numpy functions (you could use opencv to export image)

# With opencv
Rotate image with OpenCV: cv2.rotate()

Flip image with OpenCV: cv2.flip()
# With numpy

Rotate image with NumPy: np.rot90()

Flip image with NumPy: np.flip()

In [28]:
import numpy as np

In [41]:
# flip vertically image
v_flip_np = image[:, ::-1]
v_flip_cv = cv2.flip(image, 1)

In [42]:
cv2.imwrite("vertical_np.jpg",v_flip_np)

True

In [43]:
cv2.imwrite("vertical_cv.jpg",v_flip_cv)

True

In [44]:
# flip horizontally image
h_flip_np = image[::-1]
h_flip_cv = cv2.flip(image, 0)

In [45]:
cv2.imwrite("horizontal_np.jpg",h_flip_np)

True

In [46]:
cv2.imwrite("horizontal_cv.jpg",h_flip_cv)

True

In [47]:
# rotate 90
ro_90_np = np.rot90(image,-1)
ro_90_cv = cv2.rotate(image,cv2.ROTATE_90_CLOCKWISE)

In [50]:
cv2.imwrite("rotate_90np.jpg",ro_90_np)

True

In [51]:
cv2.imwrite("rotate_90cv.jpg",ro_90_cv)

True

In [53]:
# rotate -90
ro_in90_np = np.rot90(image)
ro_in90_cv = cv2.rotate(image,cv2.ROTATE_90_COUNTERCLOCKWISE)

In [54]:
cv2.imwrite("rotate_in90np.jpg",ro_in90_np)

True

In [55]:
cv2.imwrite("rotate_in90cv.jpg",ro_in90_cv)

True

In [64]:
# Resize
image2_cv = cv2.resize(image, (800,450))
print(image2_cv.shape)
#image2_np = np.resize(image, (450,800))
#print(image2_np.shape)

(450, 800, 3)


In [58]:
cv2.imwrite("image2_cv.jpg",image2_cv)

True